version: "3.8"
services:
  postgres:
    container_name: rentals_db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    env_file:
      - .docker.pg.env

  pgadmin:
    container_name: rentals_pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    volumes:
      - "./data/pgadmin:/root/.pgadmin"
    env_file:
      - .docker.pgadmin.env
    depends_on:
      - postgres
